### ISSUE TITLE
revsymbol not found

### ISSUE THREAD

**Issue by aditya7395** [frej/fast-export#132]
I keep getting this issue:

Traceback (most recent call last):
  File "/Users/adshah/Desktop/fast-export/hg-fast-export.py", line 7, in <module>
    from mercurial.scmutil import revsymbol
ImportError: cannot import name revsymbol
/Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-fast-import statistics:

**Comment by Balancer** [comment]
Same error on Ubuntu Xenial.

**Comment by frej** [comment]
[This is a canned reply to issues that contain too little information for effective troubleshooting]

Please have a look at this [blog post](https://www.viget.com/articles/tips-for-writing-better-bug-reports) about writing effective bug reports. For fast-export you should at least:

- Check that you are using the latest [released hg-fast-export](https://github.com/frej/fast-export/releases).

- Check that your installed versions of Python and Mercurial meet the minimum requirements as specified in the [README](https://github.com/frej/fast-export/blob/master/README.md).

- Explain what you are trying to do, how you are doing it and in what environment.

- If your source repository is publicly available, give the URL.

- If hg-fast-export gives an error message och a backtrace, include that in the issue.

**Comment by chris-morgan** [comment]
[v180610](https://github.com/frej/fast-export/releases/tag/v180610) broke support for Mercurial < 4.6 due to e200cec39fac8a8ebb1c7d7690c00d5cb15f0c30, which is going to affect almost everyone in practice because almost no one has Mercurial 4.6 already.

You have three primary options to work around this:

- Install mercurial 4.6 via pip (if you don’t know what you’re doing with pip, I recommend against this, because global installs are a mess);
- Downgrade fast-export to [v180317](https://github.com/frej/fast-export/releases/tag/v180317);
- Include my patch at #133.

**Comment by Orabig** [comment]
I do confirm that downgrading fast-export works well. Installing additional packages when trying to migrate an old mercurial repository is generally not a good option, given that fast-export will be used in a one-shot process.

So my procedure becomes : 
```
~$ git clone https://github.com/frej/fast-export.git
~$ cd fast-export
~$ git checkout tags/v180317
~$ cd ..
~$ mkdir new_git_repo
~$ cd new_git_repo
~$ git init
~$ ../fast-export/hg-fast-export.sh -r /old_hg_repo/
```

**Comment by chris-morgan** [comment]
Why close this? It’s still a serious issue, affecting almost everyone on Linux that uses Mercurial.

**Comment by camuso** [comment]
OK, I downgraded to version v180317, and the problem is gone. 

chris-morgan is correct.  This bug needs to be fixed.

**Comment by nobody93** [comment]
I've just made a clone from master branch as of today 17 July 2018, I still have following error, is it fixed in master branch or should I go to some branch?

fast-export/hg-fast-export.py", line 7, in <module>
    from mercurial.scmutil import revsymbol
ImportError: cannot import name revsymbol

**Comment by Orabig** [comment]
It is not fixed yet in the master branch.
As I said above, you should checkout tags/v180317 to have a working version.

**Comment by slxiao** [comment]
Checking out to tags/v180317 works but when command `../fast-export/hg-fast-export.sh ` is finished, the files in current directory are all deleted, and I have to run `git stash` to recover the files.

**Comment by eirnym** [comment]
@slxiao it's better to fill new issue to really track it.

**Comment by uthadehikaru** [comment]
@slxiao you have to run "git checkout HEAD" and voila, the file comes out

**Comment by ooxi** [comment]
Can this be fixed in master? Otherwise using the [git manual's suggested approach|https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git#_mercurial] is broken on the current Ubuntu LTS (18.04).

@chris-morgan's workaround worked btw.

**Comment by alexanpe** [comment]
I encountered this problem today.  For it not to have been resolved in master in 18 months does seem a little odd.

**Comment by frej** [comment]
@alexanpe: See [this comment](https://github.com/frej/fast-export/pull/133#issuecomment-557587125) in PR #132 for why there is no support for old Mercurial revisions.

**Comment by ooxi** [comment]
@frej So first upgrading the mercurial repository and then executing fast-export should work? How about probing the repository version first and then hinting a need to upgrade to the user?

**Comment by zerkms** [comment]
For those who are as me stuck with not being able to upgrade mercurial - I created a docker image https://hub.docker.com/repository/docker/zerkms/hg-fast-export

**Comment by pqr** [comment]
> For those who are as me stuck with not being able to upgrade mercurial - I created a docker image https://hub.docker.com/r/zerkms/hg-fast-export

Great image, thank you!

But when I first run your container I got an error:
```
Status: Downloaded newer image for zerkms/hg-fast-export:latest
Error: The option core.ignoreCase is set to true in the git
repository. This will produce empty changesets for renames that just
change the case of the file name.
Use --force to skip this check or change the option with
git config core.ignoreCase false
```

So I created a Dockerfile with "--force" option:
```
FROM zerkms/hg-fast-export:latest
ENTRYPOINT ["/app/hg-fast-export.sh", "-r", "/hg", "--force"]
``` 

My be it's a good idea to add "--froce" to your docker image too?

**Comment by zerkms** [comment]
@pqr from the source code it looks like `force` disables some other checks as well. You could just add `--force` when you `docker run` the container.

**Comment by nogu3ira** [comment]
To fix:
```
sudo apt-get update
sudo apt-get install python-pip
pip install --upgrade Mercurial
```
